CREATE TABLE mytable(
   id                                                         INTEGER  PRIMARY KEY 
  ,fips                                                       INTEGER 
  ,geo_name                                                   VARCHAR(27)
  ,individual_party                                           VARCHAR(20)
  ,name_x                                                     VARCHAR(24)
  ,rank                                                       INTEGER 
  ,reporting_pct                                              NUMERIC(4,1)
  ,state                                                      VARCHAR(20)
  ,vote_pct                                                   NUMERIC(4,1)
  ,votes_x                                                    INTEGER 
  ,name_y                                                     VARCHAR(20)
  ,precincts                                                  INTEGER 
  ,results_atwoodf                                            INTEGER 
  ,results_castled                                            INTEGER 
  ,results_clintonh                                           INTEGER 
  ,results_copelands                                          INTEGER 
  ,results_de_la_fuenter                                      INTEGER 
  ,results_duncanr                                            INTEGER 
  ,results_giordanir                                          INTEGER 
  ,results_hedgesj                                            INTEGER 
  ,results_hoeflingt                                          INTEGER 
  ,results_jacobp                                             INTEGER 
  ,results_johnsong                                           INTEGER 
  ,results_kahnl                                              INTEGER 
  ,results_kenistonc                                          INTEGER 
  ,results_kennedya                                           INTEGER 
  ,results_kopitkek                                           INTEGER 
  ,results_kotlikoffl                                         INTEGER 
  ,results_la_rivag                                           INTEGER 
  ,results_lyttleb                                            INTEGER 
  ,results_maldonadoj                                         INTEGER 
  ,results_maturenm                                           INTEGER 
  ,results_mcmulline                                          INTEGER 
  ,results_mooreheadm                                         INTEGER 
  ,results_none_of_these_candidates                           INTEGER 
  ,results_scottr                                             INTEGER 
  ,results_silvar                                             INTEGER 
  ,results_skewesp                                            INTEGER 
  ,results_smithm                                             INTEGER 
  ,results_soltysike                                          INTEGER 
  ,results_steinj                                             INTEGER 
  ,results_trumpd                                             INTEGER 
  ,results_vacekd                                             INTEGER 
  ,results_whitej                                             INTEGER 
  ,votes_y                                                    INTEGER 
  ,ST                                                         VARCHAR(2)
  ,STATEFP                                                    INTEGER 
  ,dem08                                                      INTEGER 
  ,dem12                                                      INTEGER 
  ,rep08                                                      INTEGER 
  ,rep12                                                      INTEGER 
  ,tot08                                                      INTEGER 
  ,tot12                                                      INTEGER 
  ,X                                                          NUMERIC(16,8)
  ,Y                                                          NUMERIC(15,7)
  ,rep16_frac                                                 NUMERIC(11,9)
  ,dem16_frac                                                 NUMERIC(11,9)
  ,green16_frac                                               NUMERIC(11,9)
  ,libert16_frac                                              NUMERIC(11,9)
  ,rep12_frac                                                 NUMERIC(11,9)
  ,rep08_frac                                                 NUMERIC(11,9)
  ,dem12_frac                                                 NUMERIC(11,9)
  ,dem08_frac                                                 NUMERIC(11,9)
  ,X1                                                         INTEGER 
  ,County                                                     VARCHAR(42)
  ,Less_Than_High_School                                      NUMERIC(4,2)
  ,At_Least_High_School_Diploma                               NUMERIC(5,2)
  ,At_Least_Bachelor_s_Degree                                 NUMERIC(4,2)
  ,Graduate_Degree                                            NUMERIC(4,2)
  ,School_Enrollment                                          NUMERIC(5,2)
  ,Median_Earnings_2010_dollars                               NUMERIC(11,6)
  ,White_not_Latino_Population                                NUMERIC(5,2)
  ,African_American_Population                                NUMERIC(5,2)
  ,Native_American_Population                                 NUMERIC(5,2)
  ,Asian_American_Population                                  NUMERIC(5,2)
  ,Population_some_other_race_or_races                        NUMERIC(5,2)
  ,Latino_Population                                          NUMERIC(5,2)
  ,Children_Under_6_Living_in_Poverty                         NUMERIC(5,2)
  ,Adults_65_and_Older_Living_in_Poverty                      NUMERIC(5,2)
  ,Total_Population                                           NUMERIC(9,1)
  ,Preschool_Enrollment_Ratio_enrolled_ages_3_and_4           NUMERIC(4,1)
  ,Poverty_Rate_below_federal_poverty_threshold               NUMERIC(5,2)
  ,Gini_Coefficient                                           NUMERIC(5,3)
  ,Child_Poverty_living_in_families_below_the_poverty_line    NUMERIC(5,2)
  ,Management_professional_and_related_occupations            NUMERIC(5,2)
  ,Service_occupations                                        NUMERIC(5,2)
  ,Sales_and_office_occupations                               NUMERIC(5,2)
  ,Farming_fishing_and_forestry_occupations                   NUMERIC(5,2)
  ,Construction_extraction_maintenance_and_repair_occupations NUMERIC(5,2)
  ,Production_transportation_and_material_moving_occupations  NUMERIC(5,2)
  ,White                                                      NUMERIC(5,2)
  ,Black                                                      NUMERIC(5,2)
  ,Hispanic                                                   NUMERIC(5,2)
  ,Asian                                                      NUMERIC(5,2)
  ,Amerindian                                                 NUMERIC(5,2)
  ,Other                                                      NUMERIC(5,2)
  ,White_Asian                                                NUMERIC(5,2)
  ,SIRE_homogeneity                                           NUMERIC(10,8)
  ,median_age                                                 NUMERIC(4,1)
  ,lon                                                        NUMERIC(12,7)
  ,lat                                                        NUMERIC(10,7)
  ,Poor_physical_health_days                                  NUMERIC(3,1)
  ,Poor_mental_health_days                                    NUMERIC(4,1)
  ,Low_birthweight                                            NUMERIC(4,2)
  ,Teen_births                                                NUMERIC(5,1)
  ,Children_in_single_parent_households                       NUMERIC(5,3)
  ,Adult_smoking                                              NUMERIC(5,3)
  ,Adult_obesity                                              NUMERIC(5,3)
  ,Diabetes                                                   NUMERIC(5,3)
  ,Sexually_transmitted_infections                            NUMERIC(6,1)
  ,HIV_prevalence_rate                                        NUMERIC(6,1)
  ,Uninsured                                                  NUMERIC(5,3)
  ,Unemployment                                               NUMERIC(5,3)
  ,Violent_crime                                              NUMERIC(7,2)
  ,Homicide_rate                                              NUMERIC(5,2)
  ,Injury_deaths                                              NUMERIC(5,1)
  ,Infant_mortality                                           NUMERIC(4,1)
  ,CA                                                         NUMERIC(12,9)
  ,S                                                          NUMERIC(12,9)
  ,MAR                                                        NUMERIC(11,9)
  ,CFS                                                        NUMERIC(12,9)
  ,ACFS                                                       NUMERIC(11,9)
  ,MeanALC                                                    NUMERIC(11,9)
  ,MaxALC                                                     NUMERIC(11,9)
  ,Mixedness                                                  NUMERIC(12,9)
  ,elevation                                                  NUMERIC(13,9)
  ,annual_PRCP                                                NUMERIC(11,7)
  ,winter_PRCP                                                NUMERIC(12,8)
  ,summer_PRCP                                                NUMERIC(12,8)
  ,spring_PRCP                                                NUMERIC(12,8)
  ,autumn_PRCP                                                NUMERIC(11,7)
  ,annual_TAVG                                                NUMERIC(11,7)
  ,annual_TMAX                                                NUMERIC(11,7)
  ,annual_TMIN                                                NUMERIC(11,7)
  ,winter_TAVG                                                NUMERIC(11,8)
  ,winter_TMAX                                                NUMERIC(11,7)
  ,winter_TMIN                                                NUMERIC(12,9)
  ,summer_TAVG                                                NUMERIC(11,7)
  ,summer_TMAX                                                NUMERIC(11,7)
  ,summer_TMIN                                                NUMERIC(11,7)
  ,spring_TAVG                                                NUMERIC(11,7)
  ,spring_TMAX                                                NUMERIC(11,7)
  ,spring_TMIN                                                NUMERIC(11,7)
  ,autumn_TAVG                                                NUMERIC(11,7)
  ,autumn_TMAX                                                NUMERIC(11,7)
  ,autumn_TMIN                                                NUMERIC(11,7)
  ,nearest_county                                             INTEGER 
  ,temp                                                       NUMERIC(11,9)
  ,precip                                                     NUMERIC(11,7)
  ,temp_bins                                                  VARCHAR(12)
  ,lat_bins                                                   VARCHAR(11)
  ,lon_bins                                                   VARCHAR(13)
  ,precip_bins                                                VARCHAR(19)
  ,elevation_bins                                             VARCHAR(19)
);
